apiVersion: v1
kind: Pod
metadata:
  name: linode-cli
  namespace: default
spec:
  containers:
  - name: linode-cli
    image: linode/cli:latest
    command: ["sleep", "infinity"]
    env:
    - name: LINODE_CLI_TOKEN
      valueFrom:
        secretKeyRef:
          name: linode-cli-config
          key: LINODE_CLI_TOKEN
    volumeMounts:
    - name: linode-config
      mountPath: /home/cli/.config/linode-cli
  volumes:
  - name: linode-config
    emptyDir: {}
  restartPolicy: Never
